version: 0.0
os: linux

files:
  - source: /
    destinaton: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 500

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 500
  
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 500
